### ISSUE TITLE
where is gradle ?

### ISSUE THREAD

**Issue by lumpidu** [javiersantos/android-ci#12]
I can see after building the docker image that there is a gradlew file in path `/sdk/extras/google/google_play_services/samples/unified/ActivityDemo/gradlew`. Is this supposed to be the correct path for the official gradlew wrapper?

After calling this file, a directory `/root/.gradle` exists, but there is no path environment set to the gradle script inside. How can gradle be called from within the docker container ?

**Comment by lumpidu** [comment]
Never mind, please close, found it :D

**Comment by Aditya94A** [comment]
Can you please share how you found it?
