### ISSUE TITLE
Execution failed app:processDebugResources Android Studio

### ISSUE THREAD

**Issue by gokulakshay** [javiersantos/android-ci#8]
I am running with 28.0.2

Download https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/3.2.0-4818971/aapt2-3.2.0-4818971-linux.jar
:app:splitsDiscoveryTaskDebug
:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /builds/mid-android/mid-android/app/src/main/res/layout/activity_forgot_password.xml:12: error: resource font/proximanovasemibold (aka com.myidealdoctor.mid:font/proximanovasemibold) not found.
  error: failed linking file resources.
  
  Command: /builds/mid-android/mid-android/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-linux.jar/266408780c395b064f93b30e44a5071d/aapt2-3.2.0-4818971-linux/aapt2 link -I\
          /sdk/platforms/android-28/android.jar\
          --manifest\
          /builds/mid-android/mid-android/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /builds/mid-android/mid-android/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/builds/mid-android/mid-android/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /builds/mid-android/mid-android/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          com.myidealdoctor.mid\
          -0\
          apk\
          --output-text-symbols\
          /builds/mid-android/mid-android/app/build/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-linux Daemon #0
  Output:  /builds/mid-android/mid-android/app/src/main/res/layout/activity_forgot_password.xml:12: AAPT: error: resource font/proximanovasemibold (aka com.myidealdoctor.mid:font/proximanovasemibold) not found.
      
  error: failed linking file resources.
  Command: /builds/mid-android/mid-android/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.0-4818971-linux.jar/266408780c395b064f93b30e44a5071d/aapt2-3.2.0-4818971-linux/aapt2 link -I\
          /sdk/platforms/android-28/android.jar\
          --manifest\
          /builds/mid-android/mid-android/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\
          /builds/mid-android/mid-android/app/build/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\
          @/builds/mid-android/mid-android/app/build/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\
          --java\
          /builds/mid-android/mid-android/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\
          com.myidealdoctor.mid\
          -0\
          apk\
          --output-text-symbols\
          /builds/mid-android/mid-android/app/build/intermediates/symbols/debug/R.txt\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.0-4818971-linux Daemon #0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 40s
17 actionable tasks: 17 executed
ERROR: Job failed: exit code 1

**Comment by javiersantos** [comment]
The image is working fine, there is something wrong with your project and it can't compile. Check your project.
